name: Deploy Angular 20 to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write    # Permiso para empujar la rama gh-pages
  pages: write      # Permiso para publicar en GitHub Pages
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: |
          npm run build -- --configuration production \
            --base-href "/perfil/"
        env:
          CI: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist/my-profile
          force_orphan: true     # crea un commit huérfano para limpiar archivos previos
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
